### ISSUE TITLE
Crux's not working properly with DnD v4.3.1

### ISSUE THREAD

**Issue by pefcs** [Relic-Repo/crux#12]
Hi,

While it was working great with DnD v4.2.2, after updating to v4.3.1 the HUD stopped functioning.

The sidebar is completely empty, no matter which actor I'm targeting.

![Image](https://github.com/user-attachments/assets/a0525454-c566-4134-b29d-069063bd9040)

The following error is visible in the console log:

```
foundry.js:8063 Uncaught (in promise) TypeError: undefined. value.toFixed is not a function
[Detected 1 package: crux(v1.1.1)]
    at Object.numberFormat (foundry.js:8063:51)
    at Object.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:19:157)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at handlebars.min.js:27:7576
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7544
    at Object.<anonymous> (handlebars.min.js:27:7619)
    at Object.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:29:49)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at Object.<anonymous> (handlebars.min.js:27:7333)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:13:49)
    at c (handlebars.min.js:27:23534)
    at f (handlebars.min.js:27:19895)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async updateTray (cruxTrayUI.js:432:24)
```

Foundry version: v12
DnD version: 4.3.1

**Comment by eyalhaim1** [comment]
Same here.
Great UI!! THANK YOU

**Comment by Zimnior12** [comment]
I got it working after getting some help from ChatGP. If anyone wants to use Crux in latest dnd here are the 2 updated files. Changed were made to cruxHooks.js and crux.hbs
Apparently non-numeric values were passed to numberFormat in crux.hbs, causing issues.

[crux_fixed_v2.zip](https://github.com/user-attachments/files/18893130/crux_fixed_v2.zip)

**Comment by pefcs** [comment]
Cool. With the change above it works again. Thanks a lot!

**Comment by Relic-Repo** [comment]
Repaired in version 1.2.0. Issue Closed.
